# Generated by Django 3.1.7 on 2021-03-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CardNumber', models.IntegerField()),
                ('PIN', models.PositiveSmallIntegerField()),
                ('CVV', models.PositiveSmallIntegerField()),
                ('Balance', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
